feat: jwt 설정
Wanted-Pre-Onboarding-Backend7-R/sns-feed-integration pull request #17
Opened 2023-10-26 10:36 UTC by sohyuneeee

## 📃 설명

- resolves #12 
- 

## 🔨 작업 내용

1. 
2. 
3. 

## 💬 기타 사항

-

2023-10-27 02:16 UTC, JoonheeJeong reviewed
시큐리티 설정 하느라 고생 많으셨습니다!

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/domain/UserDetailsImpl.java
> +public class UserDetailsImpl implements UserDetails {
아까 구두로 말씀드리기도 했지만 Member 엔티티가 직접 UserDetails를 implements 하는 방법도 있습니다! 참고입니다~

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtAccessDeniedHandler.java
> +        response.setContentType("application/json;charset=UTF-8");
직접 수기로 입력하는 대신 스프링에서 제공하는 MediaType.APPLICATION_JSON 상수와
HttpHeaders.CONTENT_ENCODING, Encoding.DEFAULT_CHARSET.name() 인코딩 헤더 설정도 가능합니다!
참고에요~ㅎㅎ

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
> +                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
반복되는 응답 설정 로직은 에러코드와 status를 인자로 받아서 별도의 메소드로 추출해도 좋을 것 같아요!

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
> +        long now = (new Date().getTime());
요기 메소드 이름에 '현' 이라고 이상한 글자가 덧붙여졌네요 ㅋㅋ

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
> +            log.info("JWT 토큰이 잘못되었습니다.");
에러코드 enum에 작성한 메시지 상수를 활용해도 좋을 것 같아요!

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/UserDetailsServiceImpl.java
> +public class UserDetailsServiceImpl implements UserDetailsService {
UserDetailsService도 MemberService에서 implements 할 수 있습니다~ 참고용입니다!

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/security/JwtSecurityConfig.java
> +    }
config 자체를 별도로 만드셔서 빼셨군요~~ 👍🏼

2023-10-27 02:16 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/domain/RefreshToken.java
> +    private String value;
Lob을 쓰셨는데, 리프레시 토큰 길이가 255자가 넘나요? 몰라서 여쭤봅니다!

2023-10-27 06:59 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/domain/UserDetailsImpl.java
> +public class UserDetailsImpl implements UserDetails {
넵! 한 번 찾아볼게요!! 감사합니다~

2023-10-27 07:02 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
> +                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
네! 리팩토링 할 때 참고해서 적용시켜 볼게요!! 감사합니다!

2023-10-27 07:03 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
> +        long now = (new Date().getTime());
커밋 메세지 작성하면 맨 마지막 글자가 저럴 때가 있더라구요😅 다음엔 확인을 잘 해볼게요~~

2023-10-27 07:04 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
> +            log.info("JWT 토큰이 잘못되었습니다.");
이것도 같이 리팩토링 해볼게요!!

2023-10-27 07:22 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/domain/RefreshToken.java
> +    private String value;
리프레시 토큰길이가 약 100 글자 정도고 상황에 따라 길이가 달라져서 텍스트 타입으로 지정을 하기 위해서
`@Column(columnDefinition = "TEXT")`
이거를 사용하려고했었어요!  
그러다가 텍스트 타입에 대해서 검색을 해봤는데 `@lob ` 으로 쓸 수 있는 방법도 있다고 해서 적용을 하였는데
지금 다시보니 PostgreSQL 환경에서 `@Column(columnDefinition = "TEXT")` 대신 롭을 쓰는 것을 권장하는 거였더라구요 ㅎㅎ
다시 수정해놓아야겠어요! 리뷰 꼼꼼히 해주셔서 감사합니다!!!

2023-10-27 16:57 UTC, mojh7 approved these changes
저도 시큐리티랑 jwt 설정할 때 비슷한 방식으로 작성했던 것 같고
구현에 대해서는 만드는 사람 마다 차이가 있는 것 같아서 오타나 코드 위주로 봤습니다.

리뷰 내용은 참고해보시면 좋을 것 같은 내용들 위주로 작성했고 다음 작업도 하셔야되니 승인 처리했습니다. 고생하셨습니다!!

2023-10-27 16:57 UTC, mojh7 commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
> +    public static final String AUTHORIZATION_HEADER = "Authorization";
이거는 보셨을 수도 있겠지만 `HttpHeaders` 에다가 . 만 기입해서 정적 변수나 함수 살펴보시면 spring 프레임워크에서 Authorization header field를 정의한게 있더라구요
``` java
// org.springframework.http.HttpHeaders
/**
 * The HTTP {@code Authorization} header field name.
 * @see <a href="https://tools.ietf.org/html/rfc7235#section-4.2">Section 4.2 of RFC 7235</a>
 */
public static final String AUTHORIZATION = "Authorization";
```

바로 밑에 작성하신 `public static String AUTHORITIES_KEY = "auth";` 와 같이 저희 서비스에서 따로 관리하는 key값 이름 같은거면 따로 정의하는게 맞겠지만
해당 클래스에서 `StringUtils.hasText`나 `SC_BAD_REQUEST` 쓰신거랑 비슷한 맥락으로 개발에 필요한 내용이 미리 정의된 내용이 있으면 중복 정의 하지 않고 쓰는게 좋지 않을까? 라는 개인적인 생각으로 코멘트 달았습니다

물론 `"Authorization"` 문자열 값을 저희가 따로 정의한 것이 아닌 프레임워크나 라이브러리에서 이미 정의한 값을 쓰면 정의된 곳에서 값이 변경되면 저희도 영향이 가고 특정 프레임워크(Spring)에 종속된 개념이면 사용하지 않을 수도 있을 것 같습니다. 그런데  `HttpHeaders.AUTHORIZATION` 선언된 곳에 주석을 보면 RFC 표준 문서 링크를 적어 놓았더라구요.

2023-10-27 16:57 UTC, mojh7 commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
> +    public static String AUTHORITIES_KEY = "auth";
바로 위에 34, 35번 라인의 변수를 정의한 것을 보면 원래는 `public static final String AUTHORITIES_KEY = "auth";` 이렇게 final 붙여서 정의하려고 하셨던게 아닐까 추측해봅니다

2023-10-27 16:57 UTC, mojh7 commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/UserDetailsServiceImpl.java
> +        Optional<Member> optionalMember = memberRepository.findByAccountName(accountName);
https://www.latera.kr/blog/2019-07-02-effective-optional/
이 글에서 2, 5, 7번

https://dzone.com/articles/using-optional-correctly-is-not-optional
여기서는 5, 6번을 참고하셔서

isPresent-get 이나 ifPresent-get를 orElseThrow으로 바꿔 쓰시는 방향으로 수정해보셔도 좋을 것 같습니다 😄😄

2023-10-27 16:57 UTC, mojh7 commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
> +        Member member = memberRepository.findByAccountName(memberLogInRequestDto.getAccountName())
여기를 보면 기존에 Optional 다루실 때 orElse나 orElseXXX 쓰시는 방향으로 작성하신 것 같은데
바로 이전 댓글에서 `loadUserByUsername` 에서는 따로 isPresent() 확인 후 get() 으로 작성한 이유가 따로 있었던 걸까요??

2023-10-27 16:57 UTC, mojh7 commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
> +        response.addHeader("Authorization", "Bearer " + tokenDto.getAccessToken());
이전 리뷰중에 만약 헤더 이름을`HttpHeaders.AUTHORIZATION`로 쓰시는 방향으로 수정했다면 여기도 적용해봐도 좋을 것 같습니다

2023-10-28 12:35 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
> +        Member member = memberRepository.findByAccountName(memberLogInRequestDto.getAccountName())
기능 구현 중 검색을 통해서 코드를 참조하는 상황에 제가 체크를 잘 못했습니다! 장현님 덕분에 optional 객체를 isPresent() 확인 후 get() 하는 것이 안티 패턴이라는 것을 알았어요! 수정해서 커밋하겠습니다!! 감사합니다!!!

2023-10-28 12:40 UTC, sohyuneeee commented
장현님 꼼꼼히 리뷰해주셔서 정말 감사합니다! 당장 제가 해결할 수 있는 것들은 적용해서 커밋하겠습니다! 감사합니다😄

2023-10-28 12:57 UTC, sohyuneeee commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
> +    public static final String AUTHORIZATION_HEADER = "Authorization";
HttpHeaders 클래스에 따로 정의되어 있는지 몰랐네요...! 장현님 말대로 미리 정의된 내용을 사용하는게 맞는거 같아요! 수정했습니다~ 정말 감사해요~~

2023-10-30 01:06 UTC, JoonheeJeong requested changes
화면으로 같이 봤던 부분 글로 다시 리뷰했습니다! 한 번 보시고 수정 반영해주세요!!

2023-10-30 01:06 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/controller/MemberController.java
> +
1. `@Slf4j`는 여기에 로깅 코드가 없어서 빼도 될 것 같아요!
2. MemberLogInRequest 앞에 @Validated 빠졌습니당
3. @RequestMapping("/api/members/")를 클래스에 붙여서 빼내고 포스트 매핑은 /login만 남기면 이후 코드 병합했을 때 코드가 깔끔해질 것 같습니다!

2023-10-30 01:06 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
> +    }
`@Value`를 생성자에 지정한 거 처음봤는데, 좋은 것 같아요!! 👍🏼

2023-10-30 01:06 UTC, JoonheeJeong commented on src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
> +import org.springframework.core.annotation.Order;
테스트 순서를 지정할 때는 Junit Order인데, 스프링 Order로 잘못 import 된 것 같아요!

2023-10-30 01:06 UTC, JoonheeJeong commented on src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
> +        @Order(1)
클래스에 `@TestMethodOrder`가 빠졌습니다~

2023-10-30 01:06 UTC, JoonheeJeong commented on src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
> +}
마지막 줄바꿈 추가되면 좋을 듯요! ㅎㅎ

2023-10-30 01:06 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
> +@Slf4j
로깅 안쓸거면 불필요한 애너테이션은 제거하는 게 좋을 것 같습니다!

2023-10-30 01:06 UTC, JoonheeJeong commented on src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
> +    }
1. `@Transactional` 애너테이션이 빠졌습니다!
2. 가입승인 됐는지 검증하는 로직이 추가되어야 할 것 같습니다!

2023-10-30 02:26 UTC, JoonheeJeong approved these changes
전반적으로 반영 잘 된 것 같네요! 추가적인 부분은 제가 병합 수정해보겠습니다!

2023-10-30 02:26 UTC, merged